use std::sync::atomic::{AtomicU32, Ordering};

use crossbeam_deque::Injector;
use wasm_bindgen::prelude::wasm_bindgen;
use web_sys::{
    Worker, WorkerOptions, WorkerType,
    js_sys::{self, Array},
    wasm_bindgen::{self, JsValue},
};

use crate::prelude::*;

#[wasm_bindgen(inline_js = r#"
export function glue_url(path) {
	return self.location.origin + path;
}
export function make_worker_blob_url(glueUrl) {
	const script =
		'import init, { __worker_drain, __notify_index } from ' + JSON.stringify(glueUrl) + ';\n' +
		'self.onmessage = async ({ data }) => {\n' +
		'  const [module, memory, workerId] = data;\n' +
		'  const wasm = await init({ module_or_path: module, memory });\n' +
		'  const idx = __notify_index(workerId);\n' +
		'  while (true) {\n' +
		'	 const view = new Int32Array(wasm.memory.buffer);\n' +
		'	 const seen = Atomics.load(view, idx);\n' +
		'	 if (!__worker_drain(workerId)) break;\n' +
		'	 const r = Atomics.waitAsync(view, idx, seen);\n' +
		'	 if (r.async) { await r.value; }\n' +
		'  }\n' +
		'};\n';
	const blob = new Blob([script], { type: "text/javascript" });
	return URL.createObjectURL(blob);
}
"#)]
extern "C" {
    fn glue_url(path: &str) -> String;
    fn make_worker_blob_url(glue_url: &str) -> String;
}

/// A pool of Web Workers sharing the current WASM module's memory.
///
/// Each worker runs a non-blocking drain loop in JavaScript and an `async_task` executor on
/// its microtask queue. Work runs on one of **two tracks**:
///
/// - Pinned Track: [`ThreadPool::spawn_local`]. Work that the worker "owns" forever
/// - Stelable track: [`ThreadPool::spawn`]. Work that can be done on all workers.
pub struct ThreadPool {
    workers: Vec<ThreadWorker>,
}

impl ThreadPool {
    /// Create a new thread pool with the number of workers equivalent to the reported logical
    /// core count of the browser.
    ///
    /// Worker count is fixed for the life of the pool.
    ///
    /// The `wasm_bindgen_export_path` parameter should be where your `JS` export is relative to
    /// your server. For example, if your bindgen JS is at the root of your server, this will be
    /// `ThreadPool::new("/wasm-bindgen-stuff.js")`;
    ///
    /// The worker will call functions generated by the bindgen types
    pub fn new(wasm_bindgen_export_path: &str) -> Result<Self, JsValue> {
        let url = make_worker_blob_url(&glue_url(wasm_bindgen_export_path));
        Self::new_from_absolute_url_and_count(available_parallelism(), &url)
    }

    /// Spawn a new thread pool with the provided number of workerws.
    pub fn new_with_num_workers(
        num_workers: usize,
        wasm_bindgen_export_path: &str,
    ) -> Result<Self, JsValue> {
        let url = make_worker_blob_url(&glue_url(wasm_bindgen_export_path));
        Self::new_from_absolute_url_and_count(num_workers, &url)
    }

    pub fn new_from_absolute_url_and_count(
        num_workers: usize,
        worker_script_url: &str,
    ) -> Result<Self, JsValue> {
        assert!(
            num_workers <= 32,
            "ThreadPool supports at most 32 workers (the idle bitmask is a u32)"
        );
        STATE.shutdown.store(false, Ordering::Release);

        let slots: Box<[Slot]> = (0..num_workers).map(|_| Slot::new()).collect();
        let _ = STATE.slots.set(slots);
        let _ = STATE.injector.set(Injector::new());

        let module = wasm_bindgen::module();
        let memory = wasm_bindgen::memory();

        let opts = WorkerOptions::new();
        opts.set_type(WorkerType::Module);

        let mut workers = Vec::with_capacity(num_workers);

        for id in 0..num_workers {
            let worker = Worker::new_with_options(worker_script_url, &opts)?;

            let msg = Array::of3(&module, &memory, &JsValue::from(id as u32));
            worker.post_message(&msg)?;

            workers.push(ThreadWorker {
                id: id as u32,
                inner: worker,
            });
        }

        Ok(Self { workers })
    }

    /// Spawn `Send` work (a closure or a future). Placed on the least-loaded worker.
    /// The worker will run this to completion, so it's possible to return a
    /// ```text
    /// Fut: Future<Output = T> + !Send + 'static,
    /// T: Send + 'static
    /// ```
    ///
    /// In other words, captured arguments need to be `Send`, but you may do work
    /// that is `!Send` within an async closure, like initializing a `JsValue`.
    ///
    /// You should typically utilize this over work stealing for I/O and cpu-light workloads
    pub fn spawn<M, S: Spawn<M>>(&self, work: S) -> S::Output {
        work.spawn(self)
    }

    /// Spawn `Send` work onto the work stealing queue.
    ///
    /// Unlike [`ThreadPool::spawn`], if a closure returns a `Future`, that future
    /// must also be `Send`, as it may cross a worker boundary on  every wake.
    pub fn spawn_stealable<M, S: SpawnStealable<M>>(&self, work: S) -> S::Output {
        work.spawn_stealable(self)
    }

    pub fn shutdown(&mut self) {
        STATE.shutdown.store(true, Ordering::Release);
        if let Some(slots) = STATE.slots.get() {
            for i in 0..slots.len() as u32 {
                notify_worker(i);
            }
        }

        for worker in self.workers.drain(..) {
            worker.inner.terminate();
        }
    }

    /// Returns a count of active workers
    pub fn num_workers(&self) -> usize {
        self.workers.len()
    }

    /// Returns the number of tasks that are not currently being worked on.
    pub fn num_tasks_waiting(&self) -> usize {
        let slots = STATE.slots();
        let pinned: usize = slots.iter().map(|s| s.incoming.lock().unwrap().len()).sum();
        let stealable: usize = slots.iter().map(|s| s.stealer.len()).sum();
        pinned + stealable + STATE.injector().len()
    }

    /// Is the threadpool shutdown
    pub fn is_shutdown(&self) -> bool {
        STATE.shutdown.load(Ordering::Relaxed)
    }
}

impl Drop for ThreadPool {
    fn drop(&mut self) {
        if !self.workers.is_empty() {
            self.shutdown();
        }
    }
}

pub(crate) fn place_local<F, Fut, T>(make: F) -> WorkerHandle<T>
where
    F: FnOnce() -> Fut + Send + 'static,
    Fut: Future<Output = T> + 'static,
    T: Send + 'static,
{
    let (tx, rx) = async_channel::bounded(1);
    let w = pick_worker();
    let slot = &STATE.slots()[w as usize];
    slot.load.0.fetch_add(1, Ordering::AcqRel);
    let guard = LoadGuard { load: &slot.load.0 };

    let pending = PendingSpawn::new(move |worker_id| {
        // `make` is `Send` and runs HERE, on the owner worker, so the future it produces
        // is created on the owner and never crosses a thread.
        let fut = make();
        spawn_on_worker(worker_id, async move {
            let _guard = guard;
            let result = fut.await;
            let _ = tx.try_send(result);
        });
    });

    slot.incoming.lock().unwrap().push_back(pending);
    notify_worker(w);

    WorkerHandle::new(rx)
}

pub(crate) fn place_stealable<Fut, T>(fut: Fut) -> WorkerHandle<T>
where
    Fut: Future<Output = T> + Send + 'static,
    T: Send + 'static,
{
    let (tx, rx) = async_channel::bounded(1);
    let (runnable, task) = async_task::spawn(
        async move {
            let _ = tx.try_send(fut.await);
        },
        schedule_stealable,
    );
    task.detach();
    runnable.schedule();
    WorkerHandle::new(rx)
}

/// Spawn `fut` as a detached **pinned** task pinned to `owner`. MUST be called on the owner worker
/// so the first poll is local. The counterpart to [`place_stealable`] for the pinned track: unlike
/// that safe path, a `!Send` future forces the `unsafe` `spawn_unchecked`.
fn spawn_on_worker<F>(owner: u32, fut: F)
where
    F: Future<Output = ()> + 'static,
{
    // SAFETY: the future is built on and pinned to `owner` via metadata; `schedule` always routes
    // its Runnable back to `owner`, so it is never polled on another worker. It is `'static`, so it
    // outlives the spawn.
    let (runnable, task) = unsafe {
        async_task::Builder::new()
            .metadata(owner)
            .spawn_unchecked(move |_| fut, schedule)
    };
    // Detach so dropping the JoinHandle does NOT cancel the future (callers fire-and-forget;
    // results flow out-of-band through an async_channel). Forever-futures simply never finish.
    task.detach();
    runnable.run();
}

/// The number of logical cores available to this context, read from
/// `navigator.hardwareConcurrency` and clamped to at least 1.
fn available_parallelism() -> usize {
    hardware_concurrency().filter(|&n| n > 0).unwrap_or(4)
}

fn hardware_concurrency() -> Option<usize> {
    let navigator =
        js_sys::Reflect::get(&js_sys::global(), &JsValue::from_str("navigator")).ok()?;
    js_sys::Reflect::get(&navigator, &JsValue::from_str("hardwareConcurrency"))
        .ok()?
        .as_f64()
        .map(|cores| cores as usize)
}

/// Pick the least-loaded worker for the next pinned placement.
fn pick_worker() -> u32 {
    let slots = STATE.slots();
    let mut best = 0u32;
    let mut best_load = u32::MAX;
    for (i, s) in slots.iter().enumerate() {
        let load = s.load.0.load(Ordering::Relaxed);
        if load < best_load {
            best_load = load;
            best = i as u32;
        }
    }
    best
}

/// Decrements a worker's load when the pinned future it guards completes (or is dropped). A
/// forever-future simply never drops its guard, which correctly reflects that it permanently
/// occupies a slot.
struct LoadGuard {
    load: &'static AtomicU32,
}
impl Drop for LoadGuard {
    fn drop(&mut self) {
        self.load.fetch_sub(1, Ordering::AcqRel);
    }
}
